#!/bin/bash

# Check if filename is provided
if [ -z "$1" ]
then
    echo "No filename provided. Usage: ./script.sh your_file.rs"
    exit 1
fi

# Compile the rust program
rustc $1 -o output

# Check if the compilation was successful
if [ $? -eq 0 ]
then
    ./output
    rm ./output
else
    echo "Compilation failed."
fi